{% set name = "fairseq" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/fairseq/archive/v{{ version }}.tar.gz
  sha256: 5167b8734712bb74d779dc3eb494898336ad09172478db7b238a784f49915530

build:
  number: 0
  entry_points:
    - fairseq-eval-lm = fairseq_cli.eval_lm:cli_main
    - fairseq-generate = fairseq_cli.generate:cli_main
    - fairseq-interactive = fairseq_cli.interactive:cli_main
    - fairseq-preprocess = fairseq_cli.preprocess:cli_main
    - fairseq-score = fairseq_cli.score:cli_main
    - fairseq-train = fairseq_cli.train:cli_main
    - fairseq-validate = fairseq_cli.validate:cli_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - setuptools >=18.0

  run:
    - python
    - cffi
    - {{ pin_compatible('numpy') }}
    - regex
    - sacrebleu >=1.4.12
    - cython
    - pytorch
    - tqdm
    - dataclasses
    - hydra-core

test:
  imports:
    - fairseq
    - fairseq.benchmark
  commands:
    - pip check
    - fairseq-eval-lm --help
    - fairseq-generate --help
    - fairseq-interactive --help
    - fairseq-preprocess --help
    - fairseq-score --help
    - fairseq-train --help
    - fairseq-validate --help
  requires:
    - pip
    - future

about:
  home: https://github.com/pytorch/fairseq
  summary: Facebook AI Research Sequence-to-Sequence Toolkit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
