{% set name = "fairseq" %}
{% set version = "0.12.2" %}

package:
  name: fairseq
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/facebookresearch/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  #sha256: 34f1b18426bf3844714534162f065ab733e049597476daa35fffb4d06a92b524
  sha256: b5bb076f8b0d5b06a897b11627da278816752b2202650c34becd8f4240f86961

build:
  number: 6
  entry_points:
    - fairseq-eval-lm = fairseq_cli.eval_lm:cli_main
    - fairseq-generate = fairseq_cli.generate:cli_main
    - fairseq-hydra-train = fairseq_cli.hydra_train:cli_main
    - fairseq-interactive = fairseq_cli.interactive:cli_main
    - fairseq-preprocess = fairseq_cli.preprocess:cli_main
    - fairseq-score = fairseq_cli.score:cli_main
    - fairseq-train = fairseq_cli.train:cli_main
    - fairseq-validate = fairseq_cli.validate:cli_main
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]
  # fairseq still does not support python 3.11
  # https://github.com/facebookresearch/fairseq/pull/5359/files
  skip: true  # [py>=311]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pybind11
    - python
    - pip
    - numpy
    - cython
    - setuptools
    - wheel
    # It's required to build the CPP extensions.
    - pytorch
  run:
    - python
    - hydra-core >=1.0.7
    - omegaconf
    - {{ pin_compatible('numpy') }}
    - regex
    - sacrebleu >=1.4.12
    - tqdm
    - bitarray
    - pytorch

test:
  imports:
    - fairseq
    - fairseq.benchmark
  commands:
    - fairseq-eval-lm --help
    - fairseq-generate --help
    - fairseq-interactive --help
    - fairseq-preprocess --help
    - fairseq-score --help
    - fairseq-train --help
    - fairseq-validate --help

about:
  home: https://github.com/pytorch/fairseq
  summary: Facebook AI Research Sequence-to-Sequence Toolkit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - sdvillal
